add_newline = false
command_timeout = 150

[character]
success_symbol = '[\$](bold yellow)'

## Configure the number of directories to truncate in the current path
[directory]
truncation_length = 0
truncate_to_repo = true
style = "blue"

## Configure the duration of the last command
[cmd_duration]
min_time = 100
disabled = true
style = "dimmed white"

[custom.stgit]
command = 'stg top'
when = 'stg top'
require_repo = true
style = "bold purple"
format = "[$symbol ($output )]($style)"
symbol = "î­"

[battery]
full_symbol = "ï‰€"
charging_symbol = "ó°‚„"
discharging_symbol = "ï‰„"

[jobs]
symbol = "ï£"

[package]
symbol = "ó°— "
style = "dimmed white"

[env_var.http_proxy]
symbol = "ğŸªœ"
format = "[$symbol]()"

[env_var.all_proxy]
symbol = "ğŸš‚"
format = "[$symbol]()"

# git

[git_branch]
style = "green"

[git_status]
conflicted = " ïƒ¬ "
deleted = " ó°—¨ "
modified = " ï…‹ "
stashed = " î‰€ "
staged = " ïƒ¾ "
renamed = " ï‘š "
untracked = " ï™ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
ignore_submodules = true

# language

[rust]
symbol = "î¨ "
style = "dimmed red"

[nodejs]
symbol = "ó°™ "
style = "dimmed green"

[java]
symbol = "î‰– "
style = "bold red"

[c]
symbol = "î˜ "
style = "dimmed blue"

[golang]
symbol = "î˜§ "
style = "blue"

[lua]
symbol = "î˜  "
style = "bold blue"

[python]
symbol = "îˆµ "
style = "bold yellow"

[ocaml]
symbol = "î™º "
style = "bold yellow"
